// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package ifaceoverride

import (
	"encoding/json"
)

var _ = (*cfgOverride)(nil)

// MarshalJSON marshals as JSON.
func (c Cfg) MarshalJSON() ([]byte, error) {
	type Cfg struct {
		Field Iface
	}
	var enc Cfg
	enc.Field = c.Field
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (c *Cfg) UnmarshalJSON(input []byte) error {
	type Cfg struct {
		Field *Impl
	}
	var dec Cfg
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Field != nil {
		c.Field = dec.Field
	}
	return nil
}

// MarshalYAML marshals as YAML.
func (c Cfg) MarshalYAML() (interface{}, error) {
	type Cfg struct {
		Field Iface
	}
	var enc Cfg
	enc.Field = c.Field
	return &enc, nil
}

// UnmarshalYAML unmarshals from YAML.
func (c *Cfg) UnmarshalYAML(unmarshal func(interface{}) error) error {
	type Cfg struct {
		Field *Impl
	}
	var dec Cfg
	if err := unmarshal(&dec); err != nil {
		return err
	}
	if dec.Field != nil {
		c.Field = dec.Field
	}
	return nil
}

// MarshalTOML marshals as TOML.
func (c Cfg) MarshalTOML() (interface{}, error) {
	type Cfg struct {
		Field Iface
	}
	var enc Cfg
	enc.Field = c.Field
	return &enc, nil
}

// UnmarshalTOML unmarshals from TOML.
func (c *Cfg) UnmarshalTOML(unmarshal func(interface{}) error) error {
	type Cfg struct {
		Field *Impl
	}
	var dec Cfg
	if err := unmarshal(&dec); err != nil {
		return err
	}
	if dec.Field != nil {
		c.Field = dec.Field
	}
	return nil
}
